### PR TITLE
fixes #1: Unable to build on Ubuntu 21.10

### LINKED ISSUE #1: Unable to build on Ubuntu 21.10
Hi,

trying to build your lib (using `cargo build`, I get the attached error message:

[build.log](https://github.com/sunsetkookaburra/rust-libesedb/files/9043926/build.log)

Could you please take a look at what might be wrong?

Regards, Jan

### PR DESCRIPTION
**Pull request by janstarke**

### CODE REVIEW

**Review by sunsetkookaburra — CHANGES_REQUESTED** [review]
Thanks for your fix to the build issue. I've tested that it works, and it seems to.
Make sure you rebase or reapply the changes onto main as it is now, so that it can be tested by GitHub Actions (I've added in a workflow).
I'd just ask that you only submit changes to the `libesedb-sys/build.rs` file, and leave the `Cargo.toml` files (I want to update them when I've made a couple more changes such as re-enabling docs.rs builds).
It would also be really helpful if you could `cargo fmt` your changes.

- [ ] Rebase / reapply fix onto current main
- [x] Only modify `libesedb-sys/build.rs`
- [ ] Run `cargo fmt` on changes

**Comment by sunsetkookaburra** [comment]
Hello,
I had a go at this too yesterday, and came up with a slightly smaller solution.
I think ultimately the 'perfect' fix is to use the library's configure script, but I'll look into that later as this solution works pretty well for 64-bit systems.
Thank you for your help solving the issue, I'll create a commit with the changes I made and merge it with you as a co-author.
Regards, Oli

**Comment by janstarke** [comment]
Your fix builds on my system as well, thx for your work.

I also did a look at using the `configure` script. I used `cc` for that, but I didn't succeed so far.

I've seen that you already created a new release. Would be so kind to publish the final (Linux-buildable) release to crates.io, so that I can refer to it in my program (<https://github.com/janstarke/ntdsextract2>)?

Thank you, Jan

**Comment by sunsetkookaburra** [comment]
I had a go myself too, I'm thinking detecting `sh` then going from there is the way to go.
https://crates.io/crates/libesedb/0.1.3
https://crates.io/crates/libesedb-sys/0.1.2

**Pull request closed without merging**
